//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pack.Palau {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://localhost/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="Palau.UsingCompressUncompressSoap")]
    public interface UsingCompressUncompressSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем fullPath из пространства имен http://localhost/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UnZip", ReplyAction="*")]
        pack.Palau.UnZipResponse UnZip(pack.Palau.UnZipRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем strArFormat из пространства имен http://localhost/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/Zip", ReplyAction="*")]
        pack.Palau.ZipResponse Zip(pack.Palau.ZipRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем path из пространства имен http://localhost/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetFolders", ReplyAction="*")]
        pack.Palau.GetFoldersResponse GetFolders(pack.Palau.GetFoldersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем path из пространства имен http://localhost/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetFiles", ReplyAction="*")]
        pack.Palau.GetFilesResponse GetFiles(pack.Palau.GetFilesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем fullPath из пространства имен http://localhost/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/IsPasswordForArchive", ReplyAction="*")]
        pack.Palau.IsPasswordForArchiveResponse IsPasswordForArchive(pack.Palau.IsPasswordForArchiveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnZip", Namespace="http://localhost/", Order=0)]
        public pack.Palau.UnZipRequestBody Body;
        
        public UnZipRequest() {
        }
        
        public UnZipRequest(pack.Palau.UnZipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UnZipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fullPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inPathExtract;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userIP;
        
        public UnZipRequestBody() {
        }
        
        public UnZipRequestBody(string fullPath, string inPathExtract, string password, string userIP) {
            this.fullPath = fullPath;
            this.inPathExtract = inPathExtract;
            this.password = password;
            this.userIP = userIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnZipResponse", Namespace="http://localhost/", Order=0)]
        public pack.Palau.UnZipResponseBody Body;
        
        public UnZipResponse() {
        }
        
        public UnZipResponse(pack.Palau.UnZipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UnZipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid UnZipResult;
        
        public UnZipResponseBody() {
        }
        
        public UnZipResponseBody(System.Guid UnZipResult) {
            this.UnZipResult = UnZipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Zip", Namespace="http://localhost/", Order=0)]
        public pack.Palau.ZipRequestBody Body;
        
        public ZipRequest() {
        }
        
        public ZipRequest(pack.Palau.ZipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ZipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strArFormat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strComprLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strComprMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string outPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool isRemove;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public pack.Palau.ArrayOfString arFiles;
        
        public ZipRequestBody() {
        }
        
        public ZipRequestBody(string strArFormat, string strComprLevel, string strComprMethod, string outPath, string password, string userIP, bool isRemove, pack.Palau.ArrayOfString arFiles) {
            this.strArFormat = strArFormat;
            this.strComprLevel = strComprLevel;
            this.strComprMethod = strComprMethod;
            this.outPath = outPath;
            this.password = password;
            this.userIP = userIP;
            this.isRemove = isRemove;
            this.arFiles = arFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZipResponse", Namespace="http://localhost/", Order=0)]
        public pack.Palau.ZipResponseBody Body;
        
        public ZipResponse() {
        }
        
        public ZipResponse(pack.Palau.ZipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ZipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid ZipResult;
        
        public ZipResponseBody() {
        }
        
        public ZipResponseBody(System.Guid ZipResult) {
            this.ZipResult = ZipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFoldersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFolders", Namespace="http://localhost/", Order=0)]
        public pack.Palau.GetFoldersRequestBody Body;
        
        public GetFoldersRequest() {
        }
        
        public GetFoldersRequest(pack.Palau.GetFoldersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetFoldersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public GetFoldersRequestBody() {
        }
        
        public GetFoldersRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFoldersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFoldersResponse", Namespace="http://localhost/", Order=0)]
        public pack.Palau.GetFoldersResponseBody Body;
        
        public GetFoldersResponse() {
        }
        
        public GetFoldersResponse(pack.Palau.GetFoldersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetFoldersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pack.Palau.ArrayOfString GetFoldersResult;
        
        public GetFoldersResponseBody() {
        }
        
        public GetFoldersResponseBody(pack.Palau.ArrayOfString GetFoldersResult) {
            this.GetFoldersResult = GetFoldersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFiles", Namespace="http://localhost/", Order=0)]
        public pack.Palau.GetFilesRequestBody Body;
        
        public GetFilesRequest() {
        }
        
        public GetFilesRequest(pack.Palau.GetFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string path;
        
        public GetFilesRequestBody() {
        }
        
        public GetFilesRequestBody(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFilesResponse", Namespace="http://localhost/", Order=0)]
        public pack.Palau.GetFilesResponseBody Body;
        
        public GetFilesResponse() {
        }
        
        public GetFilesResponse(pack.Palau.GetFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public pack.Palau.ArrayOfString GetFilesResult;
        
        public GetFilesResponseBody() {
        }
        
        public GetFilesResponseBody(pack.Palau.ArrayOfString GetFilesResult) {
            this.GetFilesResult = GetFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsPasswordForArchiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsPasswordForArchive", Namespace="http://localhost/", Order=0)]
        public pack.Palau.IsPasswordForArchiveRequestBody Body;
        
        public IsPasswordForArchiveRequest() {
        }
        
        public IsPasswordForArchiveRequest(pack.Palau.IsPasswordForArchiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class IsPasswordForArchiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fullPath;
        
        public IsPasswordForArchiveRequestBody() {
        }
        
        public IsPasswordForArchiveRequestBody(string fullPath) {
            this.fullPath = fullPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsPasswordForArchiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsPasswordForArchiveResponse", Namespace="http://localhost/", Order=0)]
        public pack.Palau.IsPasswordForArchiveResponseBody Body;
        
        public IsPasswordForArchiveResponse() {
        }
        
        public IsPasswordForArchiveResponse(pack.Palau.IsPasswordForArchiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class IsPasswordForArchiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsPasswordForArchiveResult;
        
        public IsPasswordForArchiveResponseBody() {
        }
        
        public IsPasswordForArchiveResponseBody(bool IsPasswordForArchiveResult) {
            this.IsPasswordForArchiveResult = IsPasswordForArchiveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsingCompressUncompressSoapChannel : pack.Palau.UsingCompressUncompressSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsingCompressUncompressSoapClient : System.ServiceModel.ClientBase<pack.Palau.UsingCompressUncompressSoap>, pack.Palau.UsingCompressUncompressSoap {
        
        public UsingCompressUncompressSoapClient() {
        }
        
        public UsingCompressUncompressSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsingCompressUncompressSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsingCompressUncompressSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsingCompressUncompressSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pack.Palau.UnZipResponse pack.Palau.UsingCompressUncompressSoap.UnZip(pack.Palau.UnZipRequest request) {
            return base.Channel.UnZip(request);
        }
        
        public System.Guid UnZip(string fullPath, string inPathExtract, string password, string userIP) {
            pack.Palau.UnZipRequest inValue = new pack.Palau.UnZipRequest();
            inValue.Body = new pack.Palau.UnZipRequestBody();
            inValue.Body.fullPath = fullPath;
            inValue.Body.inPathExtract = inPathExtract;
            inValue.Body.password = password;
            inValue.Body.userIP = userIP;
            pack.Palau.UnZipResponse retVal = ((pack.Palau.UsingCompressUncompressSoap)(this)).UnZip(inValue);
            return retVal.Body.UnZipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pack.Palau.ZipResponse pack.Palau.UsingCompressUncompressSoap.Zip(pack.Palau.ZipRequest request) {
            return base.Channel.Zip(request);
        }
        
        public System.Guid Zip(string strArFormat, string strComprLevel, string strComprMethod, string outPath, string password, string userIP, bool isRemove, pack.Palau.ArrayOfString arFiles) {
            pack.Palau.ZipRequest inValue = new pack.Palau.ZipRequest();
            inValue.Body = new pack.Palau.ZipRequestBody();
            inValue.Body.strArFormat = strArFormat;
            inValue.Body.strComprLevel = strComprLevel;
            inValue.Body.strComprMethod = strComprMethod;
            inValue.Body.outPath = outPath;
            inValue.Body.password = password;
            inValue.Body.userIP = userIP;
            inValue.Body.isRemove = isRemove;
            inValue.Body.arFiles = arFiles;
            pack.Palau.ZipResponse retVal = ((pack.Palau.UsingCompressUncompressSoap)(this)).Zip(inValue);
            return retVal.Body.ZipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pack.Palau.GetFoldersResponse pack.Palau.UsingCompressUncompressSoap.GetFolders(pack.Palau.GetFoldersRequest request) {
            return base.Channel.GetFolders(request);
        }
        
        public pack.Palau.ArrayOfString GetFolders(string path) {
            pack.Palau.GetFoldersRequest inValue = new pack.Palau.GetFoldersRequest();
            inValue.Body = new pack.Palau.GetFoldersRequestBody();
            inValue.Body.path = path;
            pack.Palau.GetFoldersResponse retVal = ((pack.Palau.UsingCompressUncompressSoap)(this)).GetFolders(inValue);
            return retVal.Body.GetFoldersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pack.Palau.GetFilesResponse pack.Palau.UsingCompressUncompressSoap.GetFiles(pack.Palau.GetFilesRequest request) {
            return base.Channel.GetFiles(request);
        }
        
        public pack.Palau.ArrayOfString GetFiles(string path) {
            pack.Palau.GetFilesRequest inValue = new pack.Palau.GetFilesRequest();
            inValue.Body = new pack.Palau.GetFilesRequestBody();
            inValue.Body.path = path;
            pack.Palau.GetFilesResponse retVal = ((pack.Palau.UsingCompressUncompressSoap)(this)).GetFiles(inValue);
            return retVal.Body.GetFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pack.Palau.IsPasswordForArchiveResponse pack.Palau.UsingCompressUncompressSoap.IsPasswordForArchive(pack.Palau.IsPasswordForArchiveRequest request) {
            return base.Channel.IsPasswordForArchive(request);
        }
        
        public bool IsPasswordForArchive(string fullPath) {
            pack.Palau.IsPasswordForArchiveRequest inValue = new pack.Palau.IsPasswordForArchiveRequest();
            inValue.Body = new pack.Palau.IsPasswordForArchiveRequestBody();
            inValue.Body.fullPath = fullPath;
            pack.Palau.IsPasswordForArchiveResponse retVal = ((pack.Palau.UsingCompressUncompressSoap)(this)).IsPasswordForArchive(inValue);
            return retVal.Body.IsPasswordForArchiveResult;
        }
    }
}
